### ISSUE TITLE
Inaccurate trimming

### ISSUE THREAD

**Issue by moppman** [vdcrim/TrimSubs#1]
Whenever I use Trimsubs on a srt file that I extracted from a PAL dvb TS, the subs are never synced correctly. I always have to readjust all timings using SubtitleEdit. I'll gladly provide samples if you're still active here.

**Comment by vdcrim** [comment]
How are you extracting the subtitles from the transport stream? It seems to me that they are not synced with the ts to begin with.

**Comment by moppman** [comment]
I use ccextractor, and the subs are perfectly sync when I load them up with the transport stream. :(

**Comment by vdcrim** [comment]
OK I reproduced the issue. I think the switches to commercials cause some irregularities on the TS timecodes, that is you can't just pass `--fps 50` to this script and instead a timecode file is needed.

I only did a quick test with a single (very bad timed) TS file, but it seems it resolved the issue. The timecode file was obtained with MKVToolnix. Give it a try.
